django/mailinglist/urls.py
from django.urls import path

from mailinglist import views

app_name = 'mailinglist'
urlpatterns = [
    path('', views.MailingListListView.as_view(), name='mailinglist_list'),
    path('new', views.CreateMailingListView.as_view(), name='create_mailinglist'),
    path('<uuid:pk>/delete', views.DeleteMailingListView.as_view(), name='delete_mailinglist'),
    path('<uuid:pk>/manage', views.MailingListDetailView.as_view(), name='manage_mailinglist'),
    path('<uuid:mailinglist_id>/subscribe', views.SubscribeToMailingListView.as_view(), 
            name='subscribe'), 
    path('<uuid:pk>/thankyou', 
            views.ThankYouForSubscribingView.as_view(), name='subscriber_thankyou'
    ),
    path('subscribe/confirmation/<uuid:pk>', 
            views.ConfirmSubscriptonView.as_view(), name='confirm_subscription'
    ),
    path('unsubscribe/<uuid:pk>', views.UnsubscribeView.as_view(), name='unsubscribe'),
    path('<uuid:mailinglist_id>/message/new', views.CreateMessageView.as_view(), name='create_message'),
    path('message/<uuid:pk>', views.MessageDetailView.as_view(), name='view_message'),
    path('api/v1/mailing-list', views.MailingListCreateListView.as_view(), 
            name='api-mailing-list-list'      
    ),
    path('api/v1/mailinglist/<uuid:pk>', views.MailingListRetrieveUpdateDestroyView.as_view(),
            name='api-mailing-list-detail'
    ),
    path('api/v1/mailinglist/<uuid:mailing_list_id>/subscribers',
            views.SubscriberListCreateView.as_view(),
            name='api-subscriber-list'
    ),
    path('api/v1/subscriber/<uuid:pk>',
         views.SubscriberRetrieveUpdateDestroyView.as_view(),
         name='api-subscriber-detail'),
]

django/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import user.views

app_name = 'user'
urlpatterns = [
    path('register', user.views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
  />
</head>
<body>
<div class="container">
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">Mail Ape</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link"
           href="{% url 'mailinglist:mailinglist_list' %}">
          Your Mailing Lists
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link"
             href="{% url 'user:logout' %}">
            Logout
          </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link"
             href="{% url 'user:login' %}">
            Login
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
             href="{% url 'user:register' %}">
            Register
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% block body %}
  {% endblock %}
</div>
</body>
</html>