django/mailinglist/urls.py
from django.urls import path

from mailinglist import views

app_name = 'mailinglist'
urlpatterns = [
    path('', views.MailingListListView.as_view(), name='mailinglist_list'),
    path('new', views.CreateMailingListView.as_view(), name='create_mailinglist'),
    path('<uuid:pk>/delete', views.DeleteMailingListView.as_view(), name='delete_mailinglist'),
    path('<uuid:pk>/manage', views.MailingListDetailView.as_view(), name='manage_mailinglist'),
    path('<uuid:mailinglist_id>/subscribe', views.SubscribeToMailingListView.as_view(), 
            name='subscribe'), 
    path('<uuid:pk>/thankyou', 
            views.ThankYouForSubscribingView.as_view(), name='subscriber_thankyou'
    ),
    path('subscribe/confirmation/<uuid:pk>', 
            views.ConfirmSubscriptonView.as_view(), name='confirm_subscription'
    ),
    path('unsubscribe/<uuid:pk>', views.UnsubscribeView.as_view(), name='unsubscribe'),
    path('<uuid:mailinglist_id>/message/new', views.CreateMessageView.as_view(), name='create_message'),
    path('message/<uuid:pk>', views.MessageDetailView.as_view(), name='view_message'),
    path('api/v1/mailing-list', views.MailingListCreateListView.as_view(), 
            name='api-mailing-list-list'      
    ),
    path('api/v1/mailinglist/<uuid:pk>', views.MailingListRetrieveUpdateDestroyView.as_view(),
            name='api-mailing-list-detail'
    ),
    path('api/v1/mailinglist/<uuid:mailing_list_id>/subscribers',
            views.SubscriberListCreateView.as_view(),
            name='api-subscriber-list'
    ),
    path('api/v1/subscriber/<uuid:pk>',
         views.SubscriberRetrieveUpdateDestroyView.as_view(),
         name='api-subscriber-detail'),
]

django/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import user.views

app_name = 'user'
urlpatterns = [
    path('register', user.views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

django/mailinglist/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

import uuid

from mailinglist import emails, tasks


class MailingList(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    owner = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_path(self):
        return reverse('mailinglist:manage_mailinglist', kwargs={'pk': self.id})

    def user_can_use_mailing_list(self, user):
        return user == self.owner


class SubscriberManager(models.Manager):

    def confirmed_subscribers_for_mailing_list(self, mailing_list):
        qs = self.get_queryset()
        qs = qs.filter(confirmed=True)
        qs = qs.filter(mailing_list=mailing_list)
        return qs


class Subscriber(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField()
    confirmed = models.BooleanField(default=False)
    mailing_list = models.ForeignKey(to=MailingList, on_delete=models.CASCADE)

    objects = SubscriberManager()

    class Meta:
        unique_together = ['email', 'mailing_list'] 

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        '''
        override save() method. self._state.adding is status of adding current
        model to db. If it is, it is True
        '''
        is_new = self._state.adding or force_update
        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields
                    )
        if is_new and not self.confirmed:
            self.send_confirmation_email()
    
    def send_confirmation_email(self):
        #emails.send_confirmation_email(self)
        tasks.send_confirmation_email_to_subscriber.delay(self.id)


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    mailing_list = models.ForeignKey(to=MailingList, on_delete=models.CASCADE)
    subject = models.CharField(max_length=140)
    body = models.TextField()
    started = models.DateTimeField(default=None, null=True)
    finished = models.DateTimeField(default=None, null=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        is_new = self._state.adding or force_update
        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields
                    )
        if is_new:
            self.build_subscriber_message_for_message.delay(self.id)


class SubscriberMessageManager(models.Manager):

    def create_from_message(self, message):
        confirmed_subs = Subscriber.objects.\
                            confirmed_subscribers_for_mailing_list(message.mailing_list)
        return [
            self.create(message=message, subscriber=subscriber)
            for subscriber in confirmed_subs
        ]


class SubscriberMessage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    message = models.ForeignKey(to=Message, on_delete=models.CASCADE)
    subscriber = models.ForeignKey(to=Subscriber, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    sent = models.DateTimeField(default=None, null=True)
    last_attempt = models.DateTimeField(default=None, null=True)

    objects = SubscriberMessageManager()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        is_new = self._state.adding or force_update
        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields
                    )
        if is_new:
            self.send_confirmation_email()
    
    def send(self):
        tasks.send_subscriber_message.delay(self.id)

django/mailinglist/forms.py
from django import forms
from django.contrib.auth import get_user_model

from mailinglist.models import MailingList, Subscriber, Message


class SubscriberForm(forms.ModelForm):
    mailing_list = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=MailingList.objects.all(),
        disabled=True,
    )

    class Meta:
        model = Subscriber
        fields = ['mailing_list', 'email', ]

class MessageForm(forms.ModelForm):
    mailing_list = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=MailingList.objects.all(),
        disabled=True,
    )

    class Meta:
        model = Message
        fields = ['mailing_list', 'subject', 'body']

class MailingListForm(forms.ModelForm):
    owner = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    class Meta:
        model = MailingList
        fields = ['owner', 'name']

django/mailinglist/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, DeleteView, ListView
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied

from mailinglist.models import Subscriber, MailingList, Message
from mailinglist.forms import MailingListForm, SubscriberForm, MessageForm
from mailinglist.mixins import UserCanUseMailingList
from mailinglist.permissions import CanUseMailingList
from mailinglist.serializers import MailingListSerializer, SubscriberSerializer, ReadOnlyEmailSubscriberSerializer


class MailingListListView(LoginRequiredMixin, ListView):

    ## default template is [AppName]_list.html

    def get_queryset(self):
        # test_send_mail()
        return MailingList.objects.filter(owner=self.request.user)

    '''
    def test_send_mail(self):
        #test sending email only; easily to test at main page

        from django.conf import settings
        from django.core.mail import send_mail
        send_mail(
            subject = 'Welcome',
            message = 'That’s your message body',
            from_email = 'xxxxxxx@gmail.com',
            recipient_list = ['xxxxxxxx@hotmail.com.hk'],
            #auth_user = 'xxxxxxx@gmail.com',
            #auth_password = 'xxxxx',
            fail_silently = False,
        )
    '''

class CreateMailingListView(LoginRequiredMixin, CreateView):

    form_class = MailingListForm
    template_name = 'mailinglist/mailinglist_form.html'
    success_url = reverse_lazy('mailinglist:mailinglist_list')

    def get_initial(self):
        return { 'owner':self.request.user.id, }


class DeleteMailingListView(LoginRequiredMixin, UserCanUseMailingList, DeleteView):
    
    ## default template is [AppName]_confirm_delete.html

    # DeleteView uses "get_object()" implicitly; overriden by UserCanUseMailingList
    # DeleteView needs a pk
    model = MailingList
    success_url = reverse_lazy('mailinglist:mailinglist_list')


class MailingListDetailView(LoginRequiredMixin, UserCanUseMailingList, DetailView):
    
    ## default template is [AppName]_detail.html
    model = MailingList


class SubscribeToMailingListView(CreateView):
    
    form_class = SubscriberForm
    template_name = 'mailinglist/subscriber_form.html'

    def get_initial(self):
        return {'mailing_list': self.kwargs['mailinglist_id']}

    def get_success_url(self):
        return reverse(
            'mailinglist:subscriber_thankyou',
            kwargs={ 'pk': self.object.mailing_list.id }
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        mailing_list_id = self.kwargs['mailinglist_id']
        ctx['mailing_list'] = get_object_or_404(
            MailingList,
            id=mailing_list_id,
        )
        return ctx


class ThankYouForSubscribingView(DetailView):
    
    model = MailingList
    template_name = 'mailinglist/subscription_thankyou.html'


class ConfirmSubscriptonView(DetailView):

    model = Subscriber
    template_name = 'mailinglist/confirm_subscription.html'

    def get_object(self, queryset=None):
        subscriber = super().get_object(queryset=queryset)
        subscriber.confirmed = True
        subscriber.save()
        return subscriber


class UnsubscribeView(DeleteView):

    model = Subscriber
    template_name = 'mailinglist/unsubscribe.html'

    def get_success_url(self):
        mailing_list = self.object.mailing_list
        return reverse('mailinglist:subscribe', kwargs={
            'mailinglist_id': mailing_list.id
        })


class CreateMessageView(LoginRequiredMixin, CreateView):

    SAVE_ACTION = 'save'
    PREVIEW_ACTION = 'preview'

    form_class = MessageForm
    template_name = 'mailinglist/message_form.html'

    def get_success_url(self):
        return reverse('mailinglist:manage_mailinglist',
                        kwargs={'pk': self.object.mailing_list.id}
        )

    def get_initial(self):
        mailing_list = self.get_mailing_list()
        return {'mailing_list': mailing_list.id}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        mailing_list = self.get_mailing_list()
        ctx.update(
            {
                'mailing_list': mailing_list,
                'SAVE_ACTION': self.SAVE_ACTION,
                'PREVIEW_ACTION': self.PREVIEW_ACTION,
            }
        )
        return ctx

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == self.PREVIEW_ACTION:
            context = self.get_context_data(
                            form=form,
                            message=form.instance,
                        )
            return self.render_to_response(context=context)
        elif action == self.SAVE_ACTION:
            return super().form_valid(form)

    def get_mailing_list(self):
        mailing_list = get_object_or_404(MailingList, 
                                        id=self.kwargs['mailinglist_id']
                        )
        if not mailing_list.user_can_use_mailing_list(self.request.user):
            raise PermissionDenied()
        return mailing_list


class MessageDetailView(LoginRequiredMixin, UserCanUseMailingList, DetailView):
    model = Message


# ListCreateAPIView: GET  - get_queryset() with serialized content
#                    POST - create & return a MailingList model instance
class MailingListCreateListView(generics.ListCreateAPIView):
    '''
    API that lists or creates mailing list based on GET or POST requrests
    '''
    # IsAuthenticated is rest_framework's class
    # enforces that only users logged in via Django's built-in user system
    # be allowed to access REST services
    # if IsAuthenticated fails, then CanUseMailingList will not be called
    permission_classes = (IsAuthenticated, CanUseMailingList)   
    serializer_class = MailingListSerializer

    def get_queryset(self):
        return self.request.user.mailinglist_set.all()

    def get_serializer(self, *args, **kwargs):
        data = kwargs.get('data', None)
        if data:
            new_data = dict(data)
            new_data['owner'] = self.request.user.id    # override owner id
            kwargs['data'] = new_data
        return super().get_serializer(*args, **kwargs)

        # original part mentioned in book, but does not work
        #if kwargs.get('data', None):
        #    data = kwargs.get('data', None)
        #    owner = {'owner': self.request.user.id}
        #    data.update(owner)
        #    return super().get_serializer(*args, **kwargs)


class MailingListRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    '''
    API that retrieves/edit/delete mailing list by pk (id) 
    based on GET/PUT/PATCH/POST requests
    '''
    permission_classes = (IsAuthenticated, CanUseMailingList)
    serializer_class = MailingListSerializer
    queryset = MailingList.objects.all()


# Similar to MailingListCreateListView
class SubscriberListCreateView(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated, CanUseMailingList)
    serializer_class = SubscriberSerializer
    
    def get_queryset(self):
        mailing_list_pk = self.kwargs['mailing_list_pk']
        mailing_list = get_object_or_404(MailingList, id=mailing_list_pk)
        return mailing_list.subscriber_set.all()        # return subscriber model

    def get_serializer(self, *args, **kwargs):
        if kwargs.get('data'):
            data = kwargs.get('data')
            mailing_list = {
                'mailing_list': reverse('mailinglist:api-mailing-list-detail',
                    kwargs={'pk':self.kwargs['mailing_list_pk']}
                )
            }
            data.update(mailing_list)
        return super().get_serializer(*args, **kwargs)

    
class SubscriberRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthenticated, CanUseMailingList)
    serializer_class = ReadOnlyEmailSubscriberSerializer
    queryset = Subscriber.objects.all()

django/mailinglist/templates/mailinglist/confirm_subscription.html
{% extends "base.html" %}

{% block title %}
  Subscription to {{ subscriber.mailing_list }} confirmed
{% endblock %}

{% block body %}
  <h1>Subscription to {{ subscriber.mailing_list }} confirmed!</h1>
{% endblock %}

django/mailinglist/templates/mailinglist/mailinglist_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Confirm delete {{ mailinglist.name }}
{% endblock %}

{% block body %}
  <h1>Confirm Delete?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ mailinglist.name }}?</p>
    <input type="submit" value="Yes" class="btn btn-danger btn-sm ">
    <a class="btn btn-primary btn-lg" 
        href="{% url 'mailinglist:manage_mailinglist' pk=mailinglist.id %}">
      No
    </a>
  </form>
{% endblock %}

django/mailinglist/templates/mailinglist/mailinglist_detail.html
{% extends "base.html" %}

{% block title %}
  {{ mailinglist.name }} Management
{% endblock %}

{% block body %}
  <h1>{{ mailinglist.name }} Management
    <a class="btn btn-danger"
       href="{% url 'mailinglist:delete_mailinglist' pk=mailinglist.id %}">
      Delete</a>
  </h1>

  <div>
    <a href="{% url 'mailinglist:subscribe' mailinglist_id=mailinglist.id %}">
      Subscription Link</a>
  </div>

  <h2>Messages</h2>
  <div> Send new
    <a class="btn btn-primary"
       href="{% url 'mailinglist:create_message' mailinglist_id=mailinglist.id %}">
      Send new Message</a>
  </div>
  <ul>
    {% for message in mailinglist.message_set.all %}
      <li>
        <a href="{% url 'mailinglist:view_message' pk=message.id %}">{{ message.subject }}</a>
      </li>
    {% endfor %}
  </ul>

  <h2>Subscribers</h2>
  <ul>
    {% for subscriber in mailinglist.subscriber_set.all %}
      <li>
        {{ subscriber.email }}
        {{ subscriber.confirmed|yesno:"confirmed,unconfirmed" }}
        <a href="{% url 'mailinglist:unsubscribe' pk=subscriber.id %}">
          Unsubscribe
        </a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

django/mailinglist/templates/mailinglist/mailinglist_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Create Mailing List
{% endblock %}

{% block body %}
  <h1>Create Mailing List</h1>
  <form method="post" class="col-sm-4">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
{% endblock %}

django/mailinglist/templates/mailinglist/mailinglist_list.html
{% extends "base.html" %}

{% block title %}
  Your Mailing Lists
{% endblock %}

{% block body %}
  <div class="row user-mailing-lists">
    <div class="col-sm-12">
      <h1>Your Mailing Lists</h1>
      <div>
        <a class="btn btn-primary"
           href="{% url "mailinglist:create_mailinglist" %}">New List</a>
      </div>
      <p> Your mailing lists:</p>
      <ul class="mailing-list-list">
        {% for mailinglist in mailinglist_list %}
          <li class="mailinglist-item">
            <a href="{% url "mailinglist:manage_mailinglist" pk=mailinglist.id %}">
              {{ mailinglist.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

django/mailinglist/templates/mailinglist/message_detail.html
{% extends "base.html" %}

{% load markdownify %}

{% block title %}
  {{ message.subject }}
{% endblock %}

{% block body %}
  <h1>{{ message.subject }}</h1>
  <div>
    {{ message.body|markdownify }}
  </div>
{% endblock %}

django/mailinglist/templates/mailinglist/message_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% load markdownify %}

{% block title %}
  Send a message to {{ mailing_list }}
{% endblock %}

{% block body %}
  <h1>Send a message to {{ mailing_list.name }}</h1>
  {% if message %}
    <div class="card">
      <div class="card-header">
        Message Preview
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ message.subject }}</h5>
        <div>{{ message.body|markdownify }}</div>
      </div>
    </div>
  {% endif %}
  <form method="post" class="col-sm-12 col-md-9">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" name="action"
            value="{{ SAVE_ACTION }}"
            class="btn btn-primary">Save
    </button>
    <button type="submit" name="action"
            value="{{ PREVIEW_ACTION }}"
            class="btn btn-primary">Preview
    </button>

  </form>
{% endblock %}

django/mailinglist/templates/mailinglist/subscriber_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Subscribe to {{ mailing_list }}
{% endblock %}

{% block body %}
  <h1>Subscribe to {{ mailing_list }}</h1>
  <form method="post" class="col-sm-6">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
{% endblock %}

django/mailinglist/templates/mailinglist/subscription_thankyou.html
{% extends "base.html" %}

{% block title %}
  Thank you for subscribing to {{ mailinglist }}
{% endblock %}

{% block body %}
  <div class="col-sm-12">
    <h1>
      Thank you for subscribing
      to {{ mailinglist }}
    </h1>
    <p>Check your email for a confirmation email.</p>
  </div>
{% endblock %}

django/mailinglist/templates/mailinglist/unsubscribe.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Unsubscribe?
{% endblock %}

{% block body %}
  <div class="col">
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to unsubscribe
         from {{ subscriber.mailing_list.name }} ?</p>
      </p>
      <input class="btn btn-danger" type="submit" value="Yes, I want to unsubscribe">
    </form>    
  </div>
{% endblock %}